### ISSUE TITLE
Needed update for Kodi 20 - program.RockClean

### ISSUE THREAD

**Issue by aitschti** [Rockcrusher01/zips#1]
First of all, love the RockClean for Kodi 19 Add-On!

With the recently released Kodi 20, the add-on crashes in `clean.py`

All `xbmc.translatePath` need to be changed to `xbmcvfs.translatePath`. That's it and the code works again.

Cheers

**Comment by Rockcrusher01** [comment]
Thanks for the heads up. I hadn't had time till now to even try Kodi 20. Updates are coming.

**Comment by aitschti** [comment]
Hey, thanks for the update and the super quick fix! Was just about to say that starter.py needed the same fix. ;)
Great support!
